### ISSUE TITLE
using existing machine withouth added virtualization layers

### ISSUE THREAD

**Issue by akostadinov** [praveenkumar/osp4#18]
Hi, it will be very useful to allow installing on existing machine without adding virtualization layers. This is to conserve resources. Useful for example on 13/16GB laptops when software to be run is not some trivial small app.

**Comment by praveenkumar** [comment]
@akostadinov At this moment this is not possible from the installer side and some of the folks are trying to resolve it under *bring your own rhel* effort, I think it is good to observe that space to get more info.

**Comment by gbraad** [comment]
Right, and therefore this might also not be the place to solve this going forward. Should be close the issue?

**Comment by gbraad** [comment]
We decided to close this issue. It is best to look out for the roadmap of the installer to target BYOD
